Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -44,7 +44,14 @@ jobs:
           echo "CURRENT_PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
 
 
-
+      - name: Check if PR title contains fix keyword with AB#
+        run: |
+          if [[ "${{ env.CURRENT_PR_TITLE }}" =~ (?i)\bfix(?:ed|es)?\ AB#\d+\b ]]; then
+            echo "Pattern found in PR title!"
+          else
+            echo "Pattern not found in PR title!"
+            exit 1  # Optionally fail the step if the pattern is not found
+          fi
 
       - name: Check if the variable contains the pattern
         run: |
