Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -126,3 +126,20 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_ID }} \
             -d '{"title":"'"${{ env.NEW_TITLE }}"'"}'
+
+  status_report:
+    name: AB ID validation Check
+    runs-on: ubuntu-latest
+    needs: [update_title]
+    if: always()
+    steps:
+      - name: Check status of job1
+        id: check_status
+        run: |
+          if [[ "${{ needs.update_title.result }}" == "success" || "${{ needs.update_title.result }}" == "skipped" ]]; then
+            echo "Job succeeded or was skipped."
+          else
+            echo "Job failed or was cancelled."
+            exit 1
+          fi
+
